(function(){
const localToast=m=>{let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.append(x)}x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)};
const addStyle=()=>document.head.insertAdjacentHTML('beforeend',`<style>
.mobileMenuBtn{display:none;width:40px;height:40px;border:1px solid var(--line2);background:#0b121b;color:#fff;border-radius:11px;font-size:18px;cursor:pointer}.mobileMenu{display:none;position:absolute;left:10px;right:10px;top:66px;background:#0b1119;border:1px solid var(--line2);border-radius:14px;padding:8px;box-shadow:var(--shadow);z-index:80}.mobileMenu a{display:block;padding:12px;color:#aeb7c7;text-decoration:none;border-radius:9px}.mobileMenu a:hover{background:#15132a;color:#fff}.drawerBack{position:fixed;inset:0;background:rgba(0,0,0,.58);backdrop-filter:blur(4px);display:none;z-index:85}.drawerBack.show{display:block}.drawer{position:absolute;left:10px;right:10px;bottom:10px;background:#0b1119;border:1px solid var(--line2);border-radius:16px;padding:16px}.drawer h3{margin:0 0 10px}.drawerGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.drawerGrid .btn{width:100%}@media(max-width:640px){.mobileMenuBtn{display:inline-flex;align-items:center;justify-content:center}.nav{position:relative}.navlinks{display:none!important}.navsearch{order:4;flex-basis:100%;max-width:none}.actions{margin-left:auto}.actions .ghost,.actions .primary{display:none}.mobileMenu.show{display:block}}
</style>`);
function mobileNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('.mobileMenuBtn'))return;const b=document.createElement('button');b.className='mobileMenuBtn';b.setAttribute('aria-label','Меню');b.innerHTML='☰';nav.prepend(b);const m=document.createElement('div');m.className='mobileMenu';m.innerHTML=`<a href="catalog.html">Каталог</a><a href="catalog.html?type=games">Игры</a><a href="catalog.html?type=keys">Ключи</a><a href="catalog.html?type=dlc">DLC</a><a href="catalog.html?type=services">Игровые услуги</a><a href="seller-dashboard.html">Продавать</a><a href="account.html">Мой FPRES</a>`;nav.append(m);b.onclick=()=>m.classList.toggle('show');m.querySelectorAll('a').forEach(a=>a.onclick=()=>m.classList.remove('show'))}
function globalLinks(){document.querySelectorAll('a[href="#"]').forEach(a=>a.onclick=e=>{e.preventDefault();localToast(a.textContent.trim()+' · демо')})}
function favorites(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>location.href='account.html?tab=favorites')}
function sellerForm(){const b=document.getElementById('add');if(!b)return;b.onclick=()=>{const modal=document.createElement('div');modal.className='drawerBack show';modal.innerHTML=`<div class="drawer"><h3>Добавить товар</h3><div class="fieldBlock"><label>Название игры</label><input class="field" id="newGame" placeholder="Например, Cyberpunk 2077"></div><div class="fieldBlock"><label>Цена</label><input class="field" id="newPrice" type="number" placeholder="2499"></div><div class="drawerGrid"><button class="btn" id="cancelNew">Отмена</button><button class="btn primary" id="saveNew">Добавить</button></div></div>`;document.body.append(modal);document.getElementById('cancelNew').onclick=()=>modal.remove();document.getElementById('saveNew').onclick=()=>{const n=document.getElementById('newGame').value.trim()||'Новый товар';localToast(n+' добавлен в демо');modal.remove()}}}
function accountTabs(){if(!location.pathname.endsWith('account.html'))return;const tab=new URLSearchParams(location.search).get('tab');if(tab==='favorites'){const fav=JSON.parse(localStorage.getItem('fpres_fav')||'[]');const items=fav.map(id=>D.games.find(g=>g.id===id)).filter(Boolean);document.querySelector('main').innerHTML=`<section class="container page"><div class="breadcrumbs"><a href="index.html">Главная</a> / Избранное</div><h1 class="pageTitle">Избранное</h1>${items.length?`<div class="gameGrid">${items.map(cardLocal).join('')}</div>`:'<div class="panel" style="padding:28px"><h3>Избранное пусто</h3><p style="color:#8490a2">Добавляй игры на странице товара.</p><a class="btn primary" href="catalog.html">В каталог</a></div>'}</section>`;bindCards()}}
const cardLocal=g=>`<article class="gameCard" data-id="${g.id}"><div class="gameCover"><img src="${fpresImg(g.id)}" alt="${g.name}"></div><div class="gameBody"><div class="gameTitle">${g.name}</div><div class="gameMeta">${g.platform} · ${g.region}</div><div class="gameBottom"><div class="gamePrice">${money(g.price)}</div><button class="gameBuy" data-add="${g.id}">Купить</button></div></div></article>`;
function bindCards(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{const id=e.currentTarget.dataset.add;const c=JSON.parse(localStorage.getItem('fpres_cart')||'[]');c.push({id,qty:1});localStorage.setItem('fpres_cart',JSON.stringify(c));localToast('Добавлено в корзину')});document.querySelectorAll('.gameCard').forEach(c=>c.onclick=e=>{if(e.target.matches('button'))return;location.href='product.html?id='+c.dataset.id})}
function productFav(){if(!location.pathname.endsWith('product.html'))return;const d=document.querySelector('.detailPanel');if(!d)return;const id=new URLSearchParams(location.search).get('id')||D.games[0].id;const btn=document.createElement('button');btn.className='miniBuy';btn.textContent='♡ В избранное';btn.style.marginTop='8px';d.insertBefore(btn,d.querySelector('.offers'));btn.onclick=()=>{let f=JSON.parse(localStorage.getItem('fpres_fav')||'[]');if(f.includes(id)){f=f.filter(x=>x!==id);localToast('Удалено из избранного')}else{f.push(id);localToast('Добавлено в избранное')}localStorage.setItem('fpres_fav',JSON.stringify(f))}}
function init(){addStyle();mobileNav();globalLinks();favorites();sellerForm();productFav();accountTabs()}
document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));
})();